# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(blank='false', max_length=15)),
                ('name', models.CharField(blank='false', max_length=15)),
                ('room', models.CharField(blank='false', max_length=5)),
                ('thing', models.CharField(blank='false', max_length=15)),
                ('description', models.CharField(blank='false', max_length=5)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
