# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='photo',
        ),
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.CharField(blank='false', max_length=50),
        ),
    ]
