# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-09 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_auto_20200208_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lost',
            name='hostel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='lost',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='lost',
            name='room',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='lost',
            name='thing',
            field=models.CharField(max_length=15),
        ),
    ]
