# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_auto_20200209_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='room',
            field=models.IntegerField(max_length=5),
        ),
    ]
