# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-10 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0008_auto_20200210_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found',
            name='image',
        ),
    ]
