# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0010_auto_20200210_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='contact',
            field=models.IntegerField(default=9999999999),
            preserve_default=False,
        ),
    ]
