# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0011_found_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
